### ISSUE TITLE
USB 失效

### ISSUE THREAD

**Issue by wang-weiing** [wecy-chen/C.H110M-K_D3_PRO#1]
您好， 我使用您的EFI文件但是只有三个USB口可用，自己定制USB文件也无效，请问可以交流一下吗？我的邮箱 wangmoacer@outlook.com

**Comment by wecy-chen** [comment]
不好意思 现在没研究这个了 给个教程地址 https://apple.sqlsec.com/6-%E5%AE%9E%E7%94%A8%E5%A7%BF%E5%8A%BF/6-1/?h=usb

**Comment by wang-weiing** [comment]
请问这块主板您还在使用吗？？

**Comment by wecy-chen** [comment]
没在用了 用macbook了
